### ISSUE TITLE
感谢分享，请问代码有对应的论文吗？

### ISSUE THREAD

**Issue by BetterG** [zssjh/semantic_slam#1]

**Comment by neocultureT** [comment]
您好，请问您在运行代码的时候遇到这个问题没有？
/home/u/桌面/semantic_slam-master/xyz_yolo.txt: 行 1: 0: 未找到命令
/home/u/桌面/semantic_slam-master/xyz_yolo.txt: 行 2: 0: 未找到命令
/home/u/桌面/semantic_slam-master/xyz_yolo.txt: 行 3: 0: 未找到命令
.
.
.
/home/u/桌面/semantic_slam-master/xyz_yolo.txt: 行 3945: 797: 未找到命令

请问这种问题该如何解决呢？谢谢！

**Comment by PYGUAN** [comment]
没遇到过，我用的desk2_yolo.txt,别的没试

**Comment by neocultureT** [comment]
您好，请问您除了配置好了opencv,pangolin,eigen3之外，系统中有没有配置yolo呢？我用了desk2_yolo.txt和相应数据集，出现的还是这个问题，不知道是不是没在系统中配置yolo，想问一下您是否配置了，谢谢！

**Comment by neocultureT** [comment]
您好，今天看了下作者的代码，发现有一些路径是作者自己的路径。目前是改了voc的路径。请问您在运行的时候还改了哪些路径呢，谢谢！

**Comment by PYGUAN** [comment]
Config.cpp 中还有一个路径要改，是rgb图像文件名，系统中没有配置yolo

**Comment by yubaoliu** [comment]
请问，你们编译代码的时候有没有遇到G2O相关的编译错误。另个，程序的运行命令（参数）是什么。
谢谢

**Comment by neocultureT** [comment]
您好，在修改了config.cpp中Detections_Align_To_File的文件路径后，一直还是之前的问题，不知道您运行程序的指令是什么，谢谢！

**Comment by neocultureT** [comment]
> 请问，你们编译代码的时候有没有遇到G2O相关的编译错误。另个，程序的运行命令（参数）是什么。
> 谢谢

一直是按照作者给的那个指令来的，也是跑不出来

**Comment by PYGUAN** [comment]
Examples/RGB-D/rgbd_tum desk2_yolo.txt Examples/RGB-D/TUM1.yaml rgbd_dataset_freiburg1_desk2 rgbd_dataset_freiburg1_desk2/associations.txt

**Comment by neocultureT** [comment]
> 请问，你们编译代码的时候有没有遇到G2O相关的编译错误。另个，程序的运行命令（参数）是什么。
> 谢谢

今天重新编译了一下，遇到了和您一样的问题，不知道怎样解决。。。

**Comment by neocultureT** [comment]
> 请问，你们编译代码的时候有没有遇到G2O相关的编译错误。另个，程序的运行命令（参数）是什么。
> 谢谢
在g2o_line_edge.h中，根据报错的几个member name，把作者注释掉的代码去掉注释，就可以编译成功了

**Comment by yubaoliu** [comment]
![image](https://user-images.githubusercontent.com/17697584/59743737-eaed6480-92ab-11e9-8d76-4d9c76741319.png)
我运行出来的结果是这样的，跟README中展示的效果不太一样。我的微信是yubao_liu
YOLO得到的结果是2D 矩形框。那个立体矩形框中的深度信息是怎么得到的啊。
谢谢

**Comment by neocultureT** [comment]
> ![image](https://user-images.githubusercontent.com/17697584/59743737-eaed6480-92ab-11e9-8d76-4d9c76741319.png)
> 我运行出来的结果是这样的，跟README中展示的效果不太一样。我的微信是yubao_liu
> YOLO得到的结果是2D 矩形框。那个立体矩形框中的深度信息是怎么得到的啊。
> 谢谢

我运行的结果也是这样。没看代码，不清楚深度信息是怎么得到的。想问一下您有没有用过desk之外的数据集运行过，能跑出来您这个截图的效果吗？我用了xyz运行，却得不到类似的结果。谢谢

**Comment by yubaoliu** [comment]
我是用 
Examples/RGB-D/rgbd_tum \
desk2_yolo.txt \
Examples/RGB-D/TUM1.yaml \
~/data/Dataset/TUM/freiburg1/rgbd_dataset_freiburg1_room \
~/data/Dataset/TUM/freiburg1/rgbd_dataset_freiburg1_room/associations.txt
跑出这个结果来的，

我也试了这个;
` ./Examples/RGB-D/rgbd_tum desk2_yolo.txt 
Examples/RGB-D/TUM1.yaml ~/data/Dataset/TUM/freiburg1/rgbd_dataset_freiburg1_desk2  ~/data/Dataset/TUM/freiburg1/rgbd_dataset_freiburg1_desk2/associations.txt
`
没有出现3D 框。
~

**Comment by neocultureT** [comment]
> 我是用
> Examples/RGB-D/rgbd_tum
> desk2_yolo.txt
> Examples/RGB-D/TUM1.yaml
> ~/data/Dataset/TUM/freiburg1/rgbd_dataset_freiburg1_room
> ~/data/Dataset/TUM/freiburg1/rgbd_dataset_freiburg1_room/associations.txt
> 跑出这个结果来的，
> 
> 我也试了这个;
> `./Examples/RGB-D/rgbd_tum desk2_yolo.txt Examples/RGB-D/TUM1.yaml ~/data/Dataset/TUM/freiburg1/rgbd_dataset_freiburg1_desk2 ~/data/Dataset/TUM/freiburg1/rgbd_dataset_freiburg1_desk2/associations.txt`
> 没有出现3D 框。
> ~

您在config.cpp用的图片的那个文件也是desk2的路径么？我跑这个数据及还是跑不出结果

**Comment by yubaoliu** [comment]
多谢，我忘记改回去了。
可以运行出结果：

![image](https://user-images.githubusercontent.com/17697584/59835433-99fd6f00-9384-11e9-91b1-4ef0446fda27.png)

 infile.open("/home/yubao/data/Project/SLAM/semantic_slam-zssjh/Filename_desk2.txt");

./Examples/RGB-D/rgbd_tum desk2_yolo.txt Examples/RGB-D/TUM1.yaml ~/data/Dataset/TUM/freiburg1/rgbd_dataset_freiburg1_desk2 ~/data/Dataset/TUM/freiburg1/rgbd_dataset_freiburg1_desk2/associations.txt

**Comment by zssjh** [comment]
@yubaoliu 不好意思才看到这些讨论，我readme里面的图的点实际上就是物体的质心，把框框注释掉就好啦

**Comment by 450932894** [comment]
你们好，请问都需要改哪些文件的路径。
我跑出来总是核心转存。
tang@D201-Tang:~/catkin_ws/src/semantic_slam_master$ ./Examples/RGB-D/rgbd_tum desk2_yolo.txt Examples/RGB-D/TUM1.yaml Date/rgbd_dataset_freiburg1_desk2 Date/rgbd_dataset_freiburg1_desk2/associations.txt 
段错误 (核心已转储)

**Comment by 450932894** [comment]
@neocultureT

**Comment by EdwiinJunior** [comment]
> 你们好，请问都需要改哪些文件的路径。
> 我跑出来总是核心转存。
> tang@D201-Tang:~/catkin_ws/src/semantic_slam_master$ ./Examples/RGB-D/rgbd_tum desk2_yolo.txt Examples/RGB-D/TUM1.yaml Date/rgbd_dataset_freiburg1_desk2 Date/rgbd_dataset_freiburg1_desk2/associations.txt
> 段错误 (核心已转储)

是gou的问题吧

**Comment by hxy1222** [comment]
@450932894 请问你问题解决了吗，我输入命令，也显示段错误（核心已转储）

**Comment by EdwiinJunior** [comment]
> 
> 
> @450932894 请问你问题解决了吗，我输入命令，也显示段错误（核心已转储）

核心已转储的可能：显卡内存太小，我的就是2G太垃圾了，等新显卡到。段错误，这个问题就复杂了，我只是核心已转储。

**Comment by hxy1222** [comment]
我电脑显卡是8G的，应该还有其他原因，请问你都修改了哪些路径呢 @EdwiinJunior

**Comment by EdwiinJunior** [comment]
> 
> 
> 我电脑显卡是8G的，应该还有其他原因，请问你都修改了哪些路径呢 @EdwiinJunior

我没跑通这个，有另一个差不多，叫orb_slam2_semantic_labelling吧(差不多就这名字），你试试那个，博客上有人跑通并记录了。你可以先跑darknet试试，看是不是你软件没装好。

**Comment by hxy1222** [comment]
> > 我电脑显卡是8G的，应该还有其他原因，请问你都修改了哪些路径呢 @EdwiinJunior
> 
> 我没跑通这个，有另一个差不多，叫orb_slam2_semantic_labelling吧(差不多就这名字），你试试那个，博客上有人跑通并记录了。你可以先跑darknet试试，看是不是你软件没装好。

orb_slam2_semantic_labelling我跑过，你意思是这个源码需要安装Darknet嘛？

**Comment by EdwiinJunior** [comment]
> 
> 
> > > 我电脑显卡是8G的，应该还有其他原因，请问你都修改了哪些路径呢 @EdwiinJunior
> > 
> > 
> > 我没跑通这个，有另一个差不多，叫orb_slam2_semantic_labelling吧(差不多就这名字），你试试那个，博客上有人跑通并记录了。你可以先跑darknet试试，看是不是你软件没装好。
> 
> orb_slam2_semantic_labelling我跑过，你意思是这个源码需要安装Darknet嘛？

不知道，因为我没跑通这个。这两个差不多

**Comment by hxy1222** [comment]
> > > > 我电脑显卡是8G的，应该还有其他原因，请问你都修改了哪些路径呢 @EdwiinJunior
> > > 
> > > 
> > > 我没跑通这个，有另一个差不多，叫orb_slam2_semantic_labelling吧(差不多就这名字），你试试那个，博客上有人跑通并记录了。你可以先跑darknet试试，看是不是你软件没装好。
> > 
> > 
> > orb_slam2_semantic_labelling我跑过，你意思是这个源码需要安装Darknet嘛？
> 
> 不知道，因为我没跑通这个。这两个差不多

哦哦，好的
